// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spotifin.Infraestrutura.Common.Contexts;

#nullable disable

namespace Spotifin.Infraestrutura.Migrations
{
    [DbContext(typeof(SpotifinDbContext))]
    [Migration("20260826172853_AddPlaylist")]
    partial class AddPlaylist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Spotifin.Dominio.Assinaturas.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoAssinatura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_playlistIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PlaylistIds");

                    b.Property<Guid>("_usuarioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.ToTable("Assinaturas");
                });

            modelBuilder.Entity("Spotifin.Dominio.Playlists.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssinaturaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
