@host=http://localhost:5267
@usuarioId=AE58C71E-5AB8-4D22-992C-5BDC196B8F3F

POST {{host}}/Assinaturas
Content-Type: application/json

{
    "TipoAssinatura": "Pro", 
    "UsuarioId": "{{usuarioId}}"
}

# {
#     "Id": "Guid",
#     "TipoAssinatura": "Gratuita", // Basica, Pro
# }