// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechFin.Spotifin.Infra.Contexts;

#nullable disable

namespace TechFin.Spotifin.Infra.Migrations
{
    [DbContext(typeof(SpotifinDbContext))]
    [Migration("20260518014730_AjustaAssinatura")]
    partial class AjustaAssinatura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TechFin.Spotifin.Dominio.Assinaturas.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoAssinatura")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assinaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
