@host = http://localhost:5055
@usuarioId = 9bb04694-a821-43d1-a802-7723bbfed0e5

@assinaturaId = ce7a3e1b-356e-4d04-818c-827cd54bab7e

// Obter as assinaturas de um usuário específico
GET {{host}}/assinaturas/{{assinaturaId}}

###

// Criar uma nova assinatura para um usuário
POST {{host}}/assinaturas
Content-Type: application/json
{
  "TipoAssinatura": "Gratis",
  "UsuarioId": "{{usuarioId}}"
}